# Generated by Django 5.0.4 on 2024-04-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdopcionGato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=100)),
                ("correo_electronico", models.EmailField(max_length=254)),
                ("telefono", models.IntegerField(max_length=20)),
                ("tipo_vivienda", models.CharField(max_length=100)),
                ("seguridad", models.TextField()),
                ("personas_conviven", models.IntegerField()),
                ("hijos", models.BooleanField()),
                ("otras_mascotas", models.BooleanField()),
                ("carnet_vacunacion_al_dia", models.BooleanField()),
                ("relacion_con_otros_animales", models.TextField()),
                ("fecha_publicacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AdopcionPerro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=100)),
                ("correo_electronico", models.EmailField(max_length=254)),
                ("telefono", models.IntegerField(max_length=20)),
                ("tipo_vivienda", models.CharField(max_length=100)),
                ("seguridad", models.TextField()),
                ("personas_conviven", models.IntegerField()),
                ("hijos", models.BooleanField()),
                ("otras_mascotas", models.BooleanField()),
                ("carnet_vacunacion_al_dia", models.BooleanField()),
                ("relacion_con_otros_animales", models.TextField()),
                ("fecha_publicacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("esta_en_adopcion", models.BooleanField(default=False)),
                ("esta_patrocinada", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="QuieroSerPatrocinador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=100)),
                ("correo_electronico", models.EmailField(max_length=254)),
                ("telefono", models.IntegerField(max_length=20)),
                ("nombre_empresa", models.CharField(max_length=100)),
                ("tipo_patrocinio", models.CharField(max_length=100)),
                ("mensaje", models.TextField()),
                ("fecha_publicacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
