# Generated by Django 5.0.4 on 2024-04-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BacoPet", "0002_persona_completo_formulario_adopcion_gato_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adopciongato",
            name="completado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="adopcionperro",
            name="completado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quieroserpatrocinador",
            name="completado",
            field=models.BooleanField(default=False),
        ),
    ]
