# Generated by Django 5.0.4 on 2024-04-22 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("BacoPet", "0003_adopciongato_completado_adopcionperro_completado_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="persona",
            old_name="nombre",
            new_name="nombre_completo",
        ),
    ]
